/*************************************************************************
 * Written in 2023-2024 by Gregory Sanders and Sivaram Dhakshinamoorthy  *
 * To the extent possible under law, the author(s) have dedicated all    *
 * copyright and related and neighboring rights to the software in this  *
 * file to the public domain worldwide. This software is distributed     *
 * without any warranty. For the CC0 Public Domain Dedication, see       *
 * EXAMPLES_COPYING or https://creativecommons.org/publicdomain/zero/1.0 *
 *************************************************************************/

#include <stdio.h>
#include <assert.h>
#include <string.h>

#include <secp256k1.h>
#include <secp256k1_schnorrsig.h>
#include <secp256k1_schnorr_adaptor.h>

#include "examples_util.h"
/* TODO: what's Z+A+B?*/
int main(void) {
    unsigned char msg[12] = "Hello World!";
    unsigned char msg_hash[32];
    unsigned char tag[17] = "my_fancy_protocol";
    unsigned char alice_seckey[32];
    unsigned char signature[64];
 	/* Includes signature parity bit so one larger */
    unsigned char pre_signature[65];
    int is_signature_valid;
    int return_val;
    secp256k1_xonly_pubkey alice_pubkey;
    secp256k1_keypair alice_keypair;

	/* Adaptor point T that Alice commits in her pre-signature */
	secp256k1_pubkey adaptor_pk;
    /* Adaptor point T' (identical to T), extracted by Bob from
     * Alice's pre-signature. */
    secp256k1_pubkey extracted_adaptor_pk;

    /* Secret adaptor t (discrete log of T) that Bob will learn,
     * for instance, the upstream PTLC secret he discovers. */
	unsigned char sec_adaptor[32];
	/* Secret adaptor t' (identical to t) that Alice extracts from
     * her pre-signature and BIP340 signature  */
	unsigned char extracted_sec_adaptor[32];

    secp256k1_context* ctx = secp256k1_context_create(SECP256K1_CONTEXT_SIGN);

	/* Secret adaptor t is generated by original PTLC sender, and
     * Bob will learn it later */
	if (!fill_random(sec_adaptor, sizeof(sec_adaptor))) {
		printf("Failed to generate randomness\n");
		return 1;
	}
	/* Adaptor point T (= t*G) is given to Alice by original PTLC sender */
	return_val = secp256k1_ec_pubkey_create(ctx, &adaptor_pk, sec_adaptor);
	assert(return_val == 1);

    /* Alice generates her keypair, and the message hash to sign */
	if (!fill_random(alice_seckey, sizeof(alice_seckey))) {
		printf("Failed to generate randomness\n");
		return 1;
	}
	if (!secp256k1_keypair_create(ctx, &alice_keypair, alice_seckey)) {
		printf("Couldn't generate keypair\n");
		return 1;
	}
    return_val = secp256k1_keypair_xonly_pub(ctx, &alice_pubkey, NULL, &alice_keypair);
    assert(return_val);
    return_val = secp256k1_tagged_sha256(ctx, msg_hash, tag, sizeof(tag), msg, sizeof(msg));
    assert(return_val);

	/* Alice creates a pre-signature using the adaptor point T(=Z+A+B),
     * and sends it to Bob */
	return_val = secp256k1_schnorr_adaptor_presign(ctx, pre_signature, msg_hash, &alice_keypair, &adaptor_pk, NULL);
	assert(return_val == 1);

	/* Bob extracts T from the pre-signature */
	return_val = secp256k1_schnorr_adaptor_extract(ctx, &extracted_adaptor_pk, pre_signature, msg_hash, &alice_pubkey);
    assert(return_val == 1);
    assert(secp256k1_ec_pubkey_cmp(ctx, &adaptor_pk, &extracted_adaptor_pk) == 0);

	/* Bob forwards the PTLC. Bob's outgoing PTLC (Z+A+B+C) is claimed
     * by Carol. Bob decides to go to chain with the full signature to
     * claim PTLC, subtracting local secret `c`.
     */
	return_val = secp256k1_schnorr_adaptor_adapt(ctx, signature, pre_signature, sec_adaptor);
	assert(return_val == 1);
    /* Signature should be valid! */
    is_signature_valid = secp256k1_schnorrsig_verify(ctx, signature, msg_hash, 32, &alice_pubkey);
	assert(is_signature_valid);

	/* A full signature hits the chain. Alice recovers z+a+b; should match
     * originally embedded value. */
	return_val = secp256k1_schnorr_adaptor_extract_sec(ctx, extracted_sec_adaptor, pre_signature, signature);
	assert(return_val == 1);
	assert(memcmp(sec_adaptor, extracted_sec_adaptor, sizeof(sec_adaptor)) == 0);

	/* Alice subtracts out local blinding factor `b`, can now claim incoming
	 * PTLC from Alice with sec_adaptor(=z+a) */

	printf("Success!\n");

    return 0;
}